export const START_LOADER                   = 'START_LOADER';
export const STOP_LOADER                    = 'STOP_LOADER';
//reminder
export const CREATE_REMINDER                = 'CREATE_REMINDER';
export const CREATE_REMINDER_SUCCESS        = 'CREATE_REMINDER_SUCCESS';
export const CREATE_REMINDER_FAILURE        = 'CREATE_REMINDER_FAILURE';
export const SET_EMPTY_SNACKBAR_TEXT        = 'SET_EMPTY_SNACKBAR_TEXT';
//email
export const CONFIRM_ACCOUNT_EMAIL          = 'CONFIRM_ACCOUNT_EMAIL';
export const STOP_ALL_REMINDERS             =  'STOP_ALL_REMINDERS';
export const STOP_SPECIFIC_REMINDER         =  'STOP_SPECIFIC_REMINDER';
export const EDIT_REMINDER                  =  'EDIT_REMINDER';
export const GET_MAIN_EDIT_DATA             =  'GET_MAIN_EDIT_DATA';
export const GET_APPROVED_EDIT_DATA         =  'GET_APPROVED_EDIT_DATA';
export const GET_UNAPPROVED_MAXIMUM         =  'GET_UNAPPROVED_MAXIMUM';
export const GET_UNAPPROVED_MAXIMUM_SUCCESS =  'GET_UNAPPROVED_MAXIMUM_SUCCESS';
export const UNSUBSCRIBE_ALL                =  'UNSUBSCRIBE_ALL';
export const GET_EMAIL_FROM_TOKEN           =   'GET_EMAIL_FROM_TOKEN';
export const GET_EMAIL_FROM_TOKEN_SUCCESS   =   'GET_EMAIL_FROM_TOKEN_SUCCESS'
export const REGISTER_ACCOUNT_SUBMIT        =   'REGISTER_ACCOUNT_SUBMIT';
export const REGISTER_ACCOUNT_SUBMIT_FAILURE =  'REGISTER_ACCOUNT_SUBMIT_FAILURE';
export const REGISTER_ACCOUNT_SUBMIT_SUCCESS =  'REGISTER_ACCOUNT_SUBMIT_SUCCESS';
export const DEFAULT_EMAIL_SUCCESS          =  'DEFAULT_EMAIL_SUCCESS';
export const DFAULT_EMAIL_FAILURE           =  'DFAULT_EMAIL_FAILURE';
export const SET_EMPTY_ERROR_TEXT           =  'SET_EMPTY_ERROR_TEXT';
export const SET_RECEIVED_DATA              =  'SET_RECEIVED_DATA';
//user
export const IS_USER_LOGEDIN                = 'IS_USER_LOGEDIN';
export const LOGIN_USER_ACTION_SUCCESS      = 'LOGIN_USER_ACTION_SUCCESS';
export const LOGIN_USER_ACTION_FAILURE      = 'LOGIN_USER_ACTION_FAILURE';
export const SET_ERROR_DIALOG_TO_FALSE      = 'SET_ERROR_DIALOG_TO_FALSE';
//myAccountPage
export const GET_SPECIFIC_USER_DATA_SUCCESS = 'GET_SPECIFIC_USER_DATA_SUCCESS';
export const GET_SPECIFIC_USER_DATA_FAILURE = 'GET_SPECIFIC_USER_DATA_FAILURE';
export const SET_NEW_APPROVED_EMAIL_SUCCESS = 'SET_NEW_APPROVED_EMAIL_SUCCESS';
export const SET_NEW_APPROVED_EMAIL_FAILURE = 'SET_NEW_APPROVED_EMAIL_FAILURE';
export const REMOVE_APPROVED_EMAIL_SUCCESS  = 'REMOVE_APPROVED_EMAIL_SUCCESS';
export const REMOVE_APPROVED_EMAIL_FAILURE  = 'REMOVE_APPROVED_EMAIL_FAILURE';
export const GET_APPROVED_EMAIL_LIST_SUCCESS  = 'GET_APPROVED_EMAIL_LIST_SUCCESS';
export const GET_SPECIFIC_USER_REMINDER_DATA_SUCCESS     = 'GET_SPECIFIC_USER_REMINDER_DATA_SUCCESS';
export const CHANGE_REMINDER_FULL_LIST     = 'CHANGE_REMINDER_FULL_LIST';
